### ISSUE TITLE
error?..

### ISSUE THREAD

**Issue by shikulja** [vss-devel/zimmer#10]
```
0:08:38.056 storeDirEntry done 167928244 16 vignette.wikia.nocookie.net/dragonage/images/3/3e/Шлем_Мартереля.png/revision/latest.png
0:08:38.057 saveDirEntryIndex 27256 167928244 vignette.wikia.nocookie.net/dragonage/images/3/3e/Шлем_Мартереля.png/revision/latest.png
0:08:38.058 ClusterWriter.append true 399 30 8871 Шлем_Мартереля.html
0:08:38.059 storeDirEntry 9 File {
  nameSpace: 'A',
  path: 'Шлем_Мартереля.html',
  title: 'Шлем Мартереля',
  mimeType: 'text/html',
  revision: 143326,
  dirEntry: null,
  id: 27257,
  data:
   Promise {
     <Buffer 3c 21 64 6f 63 74 79 70 65 20 68 74 6d 6c 3e 20 3c 68 74 6d 6c 20 64 69 72 3d 22 6c 74 72 22 20 6c 61 6e 67 3d 22 65 6e 22 3e 20 3c 68 65 61 64 3e 20 ... 8821 more bytes> },
  clusterIdx: 399,
  blobIdx: 30 }
0:08:38.060 storeDirEntry done 167928363 16 Шлем_Мартереля.html
0:08:38.060 saveDirEntryIndex 27257 167928363 Шлем_Мартереля.html
0:08:38.064 ClusterWriter.append false 397 28 965 vignette.wikia.nocookie.net/dragonage/images/b/b9/Штурм_DAII.png/revision/latest/scale-to-width-down/20.png
0:08:38.065 storeDirEntry 1 File {
  nameSpace: 'I',
  path:
   'vignette.wikia.nocookie.net/dragonage/images/b/b9/Штурм_DAII.png/revision/latest/scale-to-width-down/20.png',
  title: '',
  mimeType: 'image/png',
  revision: 0,
  dirEntry: null,
  id: 27258,
  data:
   Promise {
     <Buffer 89 50 4e 47 0d 0a 1a 0a 00 00 00 0d 49 48 44 52 00 00 00 14 00 00 00 14 08 06 00 00 00 8d 89 1d 0d 00 00 00 09 70 48 59 73 00 00 0e c4 00 00 0e c4 01 ... 915 more bytes> },
  clusterIdx: 397,
  blobIdx: 28 }
0:08:38.065 storeDirEntry done 167928440 16 vignette.wikia.nocookie.net/dragonage/images/b/b9/Штурм_DAII.png/revision/latest/scale-to-width-down/20.png
0:08:38.066 saveDirEntryIndex 27258 167928440 vignette.wikia.nocookie.net/dragonage/images/b/b9/Штурм_DAII.png/revision/latest/scale-to-width-down/20.png
vips warning: linecache: error in tile 0 x 424
0:08:38.090 Item process error vignette.wikia.nocookie.net/dragonage/images/c/c4/Щит_сэра_Уэсли.png/revision/latest.png [Error: vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit length repeat
vipspng: IDAT: invalid bit
...]
(node:12456) UnhandledPromiseRejectionWarning: ReferenceError: osProcess is not defined
    at fatal (/home/shikulja/.nvm/versions/node/v11.8.0/lib/node_modules/zimmer/zimmer.js:189:5)
    at File.process (/home/shikulja/.nvm/versions/node/v11.8.0/lib/node_modules/zimmer/zimmer.js:783:13)
(node:12456) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:12456) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
